CREATE TABLE user (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(60) NOT NULL UNIQUE,
  	password VARCHAR(60) NOT NULL
  );

CREATE TABLE todo (
	id INTEGER NOT NULL AUTO_INCREMENT,
	value VARCHAR(256) NOT NULL,
	completed BOOLEAN NOT NULL DEFAULT 0,
	userId INTEGER NOT NULL,
	PRIMARY KEY (id)
);

ALTER TABLE todo ADD CONSTRAINT todo_fk0 FOREIGN KEY (userId) REFERENCES user(id);